spring:
  application:
    name: CoffeeBackend

  datasource:
    url: jdbc:postgresql://localhost:5432/Bank
    username: root
    password: root
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    generate-ddl: true
app:
  jwt:
    secret: secretJWT
    ExpirationMs: 86400000
server.port: 8090